# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alex/git/DroneController

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alex/git/DroneController

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/git/DroneController/CMakeFiles /home/alex/git/DroneController/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/git/DroneController/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DroneController

# Build rule for target.
DroneController: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DroneController
.PHONY : DroneController

# fast build rule for target.
DroneController/fast:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/build
.PHONY : DroneController/fast

#=============================================================================
# Target rules for targets named DroneController_autogen

# Build rule for target.
DroneController_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DroneController_autogen
.PHONY : DroneController_autogen

# fast build rule for target.
DroneController_autogen/fast:
	$(MAKE) -f CMakeFiles/DroneController_autogen.dir/build.make CMakeFiles/DroneController_autogen.dir/build
.PHONY : DroneController_autogen/fast

DroneController_autogen/mocs_compilation.o: DroneController_autogen/mocs_compilation.cpp.o

.PHONY : DroneController_autogen/mocs_compilation.o

# target to build an object file
DroneController_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/DroneController_autogen/mocs_compilation.cpp.o
.PHONY : DroneController_autogen/mocs_compilation.cpp.o

DroneController_autogen/mocs_compilation.i: DroneController_autogen/mocs_compilation.cpp.i

.PHONY : DroneController_autogen/mocs_compilation.i

# target to preprocess a source file
DroneController_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/DroneController_autogen/mocs_compilation.cpp.i
.PHONY : DroneController_autogen/mocs_compilation.cpp.i

DroneController_autogen/mocs_compilation.s: DroneController_autogen/mocs_compilation.cpp.s

.PHONY : DroneController_autogen/mocs_compilation.s

# target to generate assembly for a file
DroneController_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/DroneController_autogen/mocs_compilation.cpp.s
.PHONY : DroneController_autogen/mocs_compilation.cpp.s

modules/app/app.o: modules/app/app.cpp.o

.PHONY : modules/app/app.o

# target to build an object file
modules/app/app.cpp.o:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/app/app.cpp.o
.PHONY : modules/app/app.cpp.o

modules/app/app.i: modules/app/app.cpp.i

.PHONY : modules/app/app.i

# target to preprocess a source file
modules/app/app.cpp.i:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/app/app.cpp.i
.PHONY : modules/app/app.cpp.i

modules/app/app.s: modules/app/app.cpp.s

.PHONY : modules/app/app.s

# target to generate assembly for a file
modules/app/app.cpp.s:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/app/app.cpp.s
.PHONY : modules/app/app.cpp.s

modules/gui/DroneControllerWindow.o: modules/gui/DroneControllerWindow.cpp.o

.PHONY : modules/gui/DroneControllerWindow.o

# target to build an object file
modules/gui/DroneControllerWindow.cpp.o:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/gui/DroneControllerWindow.cpp.o
.PHONY : modules/gui/DroneControllerWindow.cpp.o

modules/gui/DroneControllerWindow.i: modules/gui/DroneControllerWindow.cpp.i

.PHONY : modules/gui/DroneControllerWindow.i

# target to preprocess a source file
modules/gui/DroneControllerWindow.cpp.i:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/gui/DroneControllerWindow.cpp.i
.PHONY : modules/gui/DroneControllerWindow.cpp.i

modules/gui/DroneControllerWindow.s: modules/gui/DroneControllerWindow.cpp.s

.PHONY : modules/gui/DroneControllerWindow.s

# target to generate assembly for a file
modules/gui/DroneControllerWindow.cpp.s:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/gui/DroneControllerWindow.cpp.s
.PHONY : modules/gui/DroneControllerWindow.cpp.s

modules/gui/widgets/ControllerFrame.o: modules/gui/widgets/ControllerFrame.cpp.o

.PHONY : modules/gui/widgets/ControllerFrame.o

# target to build an object file
modules/gui/widgets/ControllerFrame.cpp.o:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/gui/widgets/ControllerFrame.cpp.o
.PHONY : modules/gui/widgets/ControllerFrame.cpp.o

modules/gui/widgets/ControllerFrame.i: modules/gui/widgets/ControllerFrame.cpp.i

.PHONY : modules/gui/widgets/ControllerFrame.i

# target to preprocess a source file
modules/gui/widgets/ControllerFrame.cpp.i:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/gui/widgets/ControllerFrame.cpp.i
.PHONY : modules/gui/widgets/ControllerFrame.cpp.i

modules/gui/widgets/ControllerFrame.s: modules/gui/widgets/ControllerFrame.cpp.s

.PHONY : modules/gui/widgets/ControllerFrame.s

# target to generate assembly for a file
modules/gui/widgets/ControllerFrame.cpp.s:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/gui/widgets/ControllerFrame.cpp.s
.PHONY : modules/gui/widgets/ControllerFrame.cpp.s

modules/gui/widgets/ControllerMenu.o: modules/gui/widgets/ControllerMenu.cpp.o

.PHONY : modules/gui/widgets/ControllerMenu.o

# target to build an object file
modules/gui/widgets/ControllerMenu.cpp.o:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/gui/widgets/ControllerMenu.cpp.o
.PHONY : modules/gui/widgets/ControllerMenu.cpp.o

modules/gui/widgets/ControllerMenu.i: modules/gui/widgets/ControllerMenu.cpp.i

.PHONY : modules/gui/widgets/ControllerMenu.i

# target to preprocess a source file
modules/gui/widgets/ControllerMenu.cpp.i:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/gui/widgets/ControllerMenu.cpp.i
.PHONY : modules/gui/widgets/ControllerMenu.cpp.i

modules/gui/widgets/ControllerMenu.s: modules/gui/widgets/ControllerMenu.cpp.s

.PHONY : modules/gui/widgets/ControllerMenu.s

# target to generate assembly for a file
modules/gui/widgets/ControllerMenu.cpp.s:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/gui/widgets/ControllerMenu.cpp.s
.PHONY : modules/gui/widgets/ControllerMenu.cpp.s

modules/gui/widgets/DroneFrame.o: modules/gui/widgets/DroneFrame.cpp.o

.PHONY : modules/gui/widgets/DroneFrame.o

# target to build an object file
modules/gui/widgets/DroneFrame.cpp.o:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/gui/widgets/DroneFrame.cpp.o
.PHONY : modules/gui/widgets/DroneFrame.cpp.o

modules/gui/widgets/DroneFrame.i: modules/gui/widgets/DroneFrame.cpp.i

.PHONY : modules/gui/widgets/DroneFrame.i

# target to preprocess a source file
modules/gui/widgets/DroneFrame.cpp.i:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/gui/widgets/DroneFrame.cpp.i
.PHONY : modules/gui/widgets/DroneFrame.cpp.i

modules/gui/widgets/DroneFrame.s: modules/gui/widgets/DroneFrame.cpp.s

.PHONY : modules/gui/widgets/DroneFrame.s

# target to generate assembly for a file
modules/gui/widgets/DroneFrame.cpp.s:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/gui/widgets/DroneFrame.cpp.s
.PHONY : modules/gui/widgets/DroneFrame.cpp.s

modules/gui/widgets/JoystickFrame.o: modules/gui/widgets/JoystickFrame.cpp.o

.PHONY : modules/gui/widgets/JoystickFrame.o

# target to build an object file
modules/gui/widgets/JoystickFrame.cpp.o:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/gui/widgets/JoystickFrame.cpp.o
.PHONY : modules/gui/widgets/JoystickFrame.cpp.o

modules/gui/widgets/JoystickFrame.i: modules/gui/widgets/JoystickFrame.cpp.i

.PHONY : modules/gui/widgets/JoystickFrame.i

# target to preprocess a source file
modules/gui/widgets/JoystickFrame.cpp.i:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/gui/widgets/JoystickFrame.cpp.i
.PHONY : modules/gui/widgets/JoystickFrame.cpp.i

modules/gui/widgets/JoystickFrame.s: modules/gui/widgets/JoystickFrame.cpp.s

.PHONY : modules/gui/widgets/JoystickFrame.s

# target to generate assembly for a file
modules/gui/widgets/JoystickFrame.cpp.s:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/gui/widgets/JoystickFrame.cpp.s
.PHONY : modules/gui/widgets/JoystickFrame.cpp.s

modules/joystick/joystick.o: modules/joystick/joystick.cpp.o

.PHONY : modules/joystick/joystick.o

# target to build an object file
modules/joystick/joystick.cpp.o:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/joystick/joystick.cpp.o
.PHONY : modules/joystick/joystick.cpp.o

modules/joystick/joystick.i: modules/joystick/joystick.cpp.i

.PHONY : modules/joystick/joystick.i

# target to preprocess a source file
modules/joystick/joystick.cpp.i:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/joystick/joystick.cpp.i
.PHONY : modules/joystick/joystick.cpp.i

modules/joystick/joystick.s: modules/joystick/joystick.cpp.s

.PHONY : modules/joystick/joystick.s

# target to generate assembly for a file
modules/joystick/joystick.cpp.s:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/joystick/joystick.cpp.s
.PHONY : modules/joystick/joystick.cpp.s

modules/radio/radio.o: modules/radio/radio.cpp.o

.PHONY : modules/radio/radio.o

# target to build an object file
modules/radio/radio.cpp.o:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/radio/radio.cpp.o
.PHONY : modules/radio/radio.cpp.o

modules/radio/radio.i: modules/radio/radio.cpp.i

.PHONY : modules/radio/radio.i

# target to preprocess a source file
modules/radio/radio.cpp.i:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/radio/radio.cpp.i
.PHONY : modules/radio/radio.cpp.i

modules/radio/radio.s: modules/radio/radio.cpp.s

.PHONY : modules/radio/radio.s

# target to generate assembly for a file
modules/radio/radio.cpp.s:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/radio/radio.cpp.s
.PHONY : modules/radio/radio.cpp.s

modules/settings/settings.o: modules/settings/settings.cpp.o

.PHONY : modules/settings/settings.o

# target to build an object file
modules/settings/settings.cpp.o:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/settings/settings.cpp.o
.PHONY : modules/settings/settings.cpp.o

modules/settings/settings.i: modules/settings/settings.cpp.i

.PHONY : modules/settings/settings.i

# target to preprocess a source file
modules/settings/settings.cpp.i:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/settings/settings.cpp.i
.PHONY : modules/settings/settings.cpp.i

modules/settings/settings.s: modules/settings/settings.cpp.s

.PHONY : modules/settings/settings.s

# target to generate assembly for a file
modules/settings/settings.cpp.s:
	$(MAKE) -f CMakeFiles/DroneController.dir/build.make CMakeFiles/DroneController.dir/modules/settings/settings.cpp.s
.PHONY : modules/settings/settings.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... DroneController"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... DroneController_autogen"
	@echo "... DroneController_autogen/mocs_compilation.o"
	@echo "... DroneController_autogen/mocs_compilation.i"
	@echo "... DroneController_autogen/mocs_compilation.s"
	@echo "... modules/app/app.o"
	@echo "... modules/app/app.i"
	@echo "... modules/app/app.s"
	@echo "... modules/gui/DroneControllerWindow.o"
	@echo "... modules/gui/DroneControllerWindow.i"
	@echo "... modules/gui/DroneControllerWindow.s"
	@echo "... modules/gui/widgets/ControllerFrame.o"
	@echo "... modules/gui/widgets/ControllerFrame.i"
	@echo "... modules/gui/widgets/ControllerFrame.s"
	@echo "... modules/gui/widgets/ControllerMenu.o"
	@echo "... modules/gui/widgets/ControllerMenu.i"
	@echo "... modules/gui/widgets/ControllerMenu.s"
	@echo "... modules/gui/widgets/DroneFrame.o"
	@echo "... modules/gui/widgets/DroneFrame.i"
	@echo "... modules/gui/widgets/DroneFrame.s"
	@echo "... modules/gui/widgets/JoystickFrame.o"
	@echo "... modules/gui/widgets/JoystickFrame.i"
	@echo "... modules/gui/widgets/JoystickFrame.s"
	@echo "... modules/joystick/joystick.o"
	@echo "... modules/joystick/joystick.i"
	@echo "... modules/joystick/joystick.s"
	@echo "... modules/radio/radio.o"
	@echo "... modules/radio/radio.i"
	@echo "... modules/radio/radio.s"
	@echo "... modules/settings/settings.o"
	@echo "... modules/settings/settings.i"
	@echo "... modules/settings/settings.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

